### ISSUE TITLE
LDA part

### ISSUE THREAD

**Issue by Dawnstar2018** [Dannynis/xvector_pytorch#2]
Sorry to bother you, but I didn't see the part of load model and trainloader in the script xvector_ext_and_lda_scatter.ipynb. Can you help me figure it out?thanks!

**Comment by Dannynis** [comment]
Sure, ive probably removed the loading cell mistakenly, have you tried torch.load?

**Comment by Dawnstar2018** [comment]
Thanks for your reply.i've try torch.load.but in vector_gpu .ipynb you are save total model,i have no idea  how to restore the last hidden layer.can you give me some advice or the loading cell you have removed?thanks a lot!

**Comment by Dannynis** [comment]
Ive updated the notebook, please try it now

**Comment by Dawnstar2018** [comment]
I got it! u r so nice!thank u !
