### ISSUE TITLE
loss change to nan

### ISSUE THREAD

**Issue by HappyGallery** [Dannynis/xvector_pytorch#6]
hey, first thanks for the great help of your code 。I  using  the dataset called cnceleb  ,but i have faced a problem .As the training goes on  the loss change to nan ,the features  i feed in the net is mfcc features gained from libROSA . And i have been debugged it  for about 2 weeks. 
input = (64,24,126) (batchsize,feature_dim,num_of_mfcc )

**Comment by lengjiayi** [comment]
Hi, I used to have the same issue: loss change to nan after first iteration.
Finally I fix it by simply remove dropout in tdnn. Hope this might help you :)

**Comment by HappyGallery** [comment]
Thanks for your advice, i would like to have a try
